import { FormEvent, useEffect, useState } from "react";

type Locale = "zh-CN" | "en";
type ImportKind = "url" | "upload" | "paste";

export type UpstreamSubscription = {
  id: string; name: string; kind: ImportKind; url?: string; userAgent?: string; configuredDocument?: string;
  proxyNodeCount: number; enabled: boolean; refreshStatus: "pending" | "success" | "stale"; lastError?: string; lastSuccessAt?: string;
  remainingTrafficBytes?: number; trafficTotalBytes?: number; trafficUsedBytes?: number; expiresAt?: string;
};

const copy = {
  "zh-CN": {
    heading: "订阅", hint: "管理订阅来源，不在此页展示节点评估结果", count: (value: number) => `${value} / 10 个订阅`, url: "订阅 URL", upload: "上传文件", paste: "粘贴 YAML", name: "名称", urlLabel: "完整 URL", userAgent: "User-Agent", file: "YAML 文件", yaml: "YAML 内容", add: "添加订阅", save: "保存更改", cancel: "取消编辑", empty: "还没有订阅。选择一种方式添加第一个订阅。", success: "刷新成功", stale: "已陈旧，使用上次成功内容", pending: "等待刷新", nodes: (value: number) => `${value} 个节点`, sourceType: "来源类型", traffic: "剩余流量", unknown: "未知", lastUpdate: "上次更新", expiry: "到期时间", refresh: "手动更新", edit: "编辑", disable: "禁用", enable: "启用", remove: "删除", limit: "最多只能添加 10 个订阅。请先删除一个订阅。", loadError: "无法读取订阅列表。", actionError: "操作失败，请重试。", defaultUserAgent: "留空时使用 Mihomo 兼容标识", requiredFile: "请选择 YAML 文件。",
  },
  en: {
    heading: "Subscriptions", hint: "Manage source subscriptions without mixing in node evaluation", count: (value: number) => `${value} / 10 Subscriptions`, url: "Subscription URL", upload: "Upload file", paste: "Paste YAML", name: "Name", urlLabel: "Full URL", userAgent: "User-Agent", file: "YAML file", yaml: "YAML content", add: "Add subscription", save: "Save changes", cancel: "Cancel edit", empty: "No subscriptions yet. Choose an import method to add the first one.", success: "Refresh successful", stale: "Stale — using last successful content", pending: "Waiting to refresh", nodes: (value: number) => `${value} nodes`, sourceType: "Source type", traffic: "Remaining traffic", unknown: "Unknown", lastUpdate: "Last update", expiry: "Expiry", refresh: "Refresh", edit: "Edit", disable: "Disable", enable: "Enable", remove: "Delete", limit: "At most 10 subscriptions are allowed. Delete one before adding another.", loadError: "Subscriptions could not be loaded.", actionError: "The operation failed. Try again.", defaultUserAgent: "Leave blank to use a Mihomo-compatible identifier", requiredFile: "Choose a YAML file.",
  },
} as const;

export default function UpstreamSubscriptions({ locale }: { locale: Locale }) {
  const text = copy[locale];
  const [subscriptions, setSubscriptions] = useState<UpstreamSubscription[]>([]);
  const [kind, setKind] = useState<ImportKind>("url"); const [name, setName] = useState(""); const [url, setURL] = useState(""); const [userAgent, setUserAgent] = useState(""); const [document, setDocument] = useState(""); const [file, setFile] = useState<File | null>(null); const [editingID, setEditingID] = useState<string | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);

  useEffect(() => { let active = true; fetch("/api/upstream-subscriptions").then(requireOK).then((response) => response.json()).then((items) => { if (active) setSubscriptions(Array.isArray(items) ? items : []); }).catch(() => { if (active) setError(text.loadError); }); return () => { active = false; }; }, [text.loadError]);
  const atLimit = subscriptions.length >= 10 && editingID === null;

  async function submit(event: FormEvent) {
    event.preventDefault(); if (atLimit) return; setBusy(true); setError("");
    try {
      let response: Response;
      if (kind === "upload" && editingID && !file) response = await fetch(`/api/upstream-subscriptions/${editingID}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, document }) });
      else if (kind === "upload") { if (!file) { setError(text.requiredFile); return; } const form = new FormData(); form.set("name", name); form.set("file", file); response = await fetch(editingID ? `/api/upstream-subscriptions/${editingID}` : "/api/upstream-subscriptions", { method: editingID ? "PUT" : "POST", body: form }); }
      else if (editingID) response = await fetch(`/api/upstream-subscriptions/${editingID}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, url, userAgent, document }) });
      else response = await fetch("/api/upstream-subscriptions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(kind === "url" ? { name, kind, url, userAgent } : { name, kind, document }) });
      const result = await readResult(response); if (!response.ok) throw new Error(result.error || text.actionError); const subscription = result as UpstreamSubscription; setSubscriptions((current) => editingID ? current.map((item) => item.id === subscription.id ? subscription : item) : [...current, subscription]); resetForm();
    } catch (failure) { setError(failure instanceof Error ? failure.message : text.actionError); } finally { setBusy(false); }
  }
  function beginEdit(subscription: UpstreamSubscription) { setEditingID(subscription.id); setKind(subscription.kind); setName(subscription.name); setURL(subscription.url || ""); setUserAgent(subscription.userAgent || ""); setDocument(subscription.configuredDocument || ""); setFile(null); setError(""); }
  async function reload() { const response = await fetch("/api/upstream-subscriptions"); if (!response.ok) throw new Error(text.loadError); setSubscriptions(await response.json()); }
  async function mutate(subscription: UpstreamSubscription, endpoint: string, init: RequestInit) { setError(""); try { const response = await fetch(endpoint, init); if (!response.ok) { const result = await readResult(response); await reload(); throw new Error(result.error || text.actionError); } const updated = await response.json() as UpstreamSubscription; setSubscriptions((current) => current.map((item) => item.id === subscription.id ? updated : item)); } catch (failure) { setError(failure instanceof Error ? failure.message : text.actionError); } }
  async function remove(subscription: UpstreamSubscription) { setError(""); try { const response = await fetch(`/api/upstream-subscriptions/${subscription.id}`, { method: "DELETE" }); if (!response.ok) throw new Error((await readResult(response)).error || text.actionError); setSubscriptions((current) => current.filter((item) => item.id !== subscription.id)); if (editingID === subscription.id) resetForm(); } catch (failure) { setError(failure instanceof Error ? failure.message : text.actionError); } }
  function resetForm() { setEditingID(null); setName(""); setURL(""); setUserAgent(""); setDocument(""); setFile(null); }

  return <section className="page" aria-labelledby="subscriptions-heading">
    <div className="pageHeading"><div><p className="eyebrow">NodeHarbor</p><h1 id="subscriptions-heading">{text.heading}</h1><p className="pageHint">{text.hint}</p></div><span className="countBadge">{text.count(subscriptions.length)}</span></div>
    <form className="panel sourceForm" onSubmit={submit}><div className="importTabs" role="group" aria-label={text.heading}>{(["url", "upload", "paste"] as ImportKind[]).map((value) => <button key={value} type="button" className={kind === value ? "active" : ""} disabled={editingID !== null} onClick={() => setKind(value)}>{value === "url" ? text.url : value === "upload" ? text.upload : text.paste}</button>)}</div><div className="formGrid"><label><span>{text.name}</span><input value={name} onChange={(event) => setName(event.target.value)} required disabled={atLimit} /></label>{kind === "url" && <><label className="wideField"><span>{text.urlLabel}</span><input type="url" value={url} onChange={(event) => setURL(event.target.value)} required disabled={atLimit} /></label><label className="wideField"><span>{text.userAgent}</span><input value={userAgent} onChange={(event) => setUserAgent(event.target.value)} placeholder={text.defaultUserAgent} disabled={atLimit} /></label></>}{kind === "upload" && <label className="wideField"><span>{text.file}</span><input type="file" accept=".yaml,.yml,application/yaml,text/yaml" onChange={(event) => setFile(event.target.files?.[0] || null)} disabled={atLimit} /></label>}{kind === "paste" && <label className="wideField"><span>{text.yaml}</span><textarea value={document} onChange={(event) => setDocument(event.target.value)} rows={7} required disabled={atLimit} /></label>}</div>{atLimit && <p className="formError" role="alert">{text.limit}</p>}{error && <p className="formError" role="alert">{error}</p>}<div className="formActions"><button className="primaryButton" type="submit" disabled={busy || atLimit}>{editingID ? text.save : text.add}</button>{editingID && <button className="secondaryButton" type="button" onClick={resetForm}>{text.cancel}</button>}</div></form>
    <div className="subscriptionList">{subscriptions.length === 0 && <p className="emptyState">{text.empty}</p>}{subscriptions.map((subscription) => <article className={`subscriptionCard ${subscription.enabled ? "" : "is-disabled"}`} key={subscription.id}><div className="cardTop"><div><h2>{subscription.name}</h2><p className="muted">{text.sourceType}: {subscription.kind === "url" ? text.url : subscription.kind === "upload" ? text.upload : text.paste}</p></div><span className={`statusPill statusPill--${subscription.refreshStatus}`}>{text[subscription.refreshStatus]}</span></div>{subscription.url && <code className="sourceURL">{subscription.url}</code>}<dl className="metadataGrid"><div><dt>{text.nodes(subscription.proxyNodeCount)}</dt><dd>{text.sourceType}</dd></div><div><dt>{formatTraffic(subscription, text.unknown)}</dt><dd>{text.traffic}</dd></div><div><dt>{formatDate(subscription.lastSuccessAt, text.unknown)}</dt><dd>{text.lastUpdate}</dd></div><div><dt>{formatDate(subscription.expiresAt, text.unknown)}</dt><dd>{text.expiry}</dd></div></dl>{subscription.lastError && <p className="sourceError" role="alert">{subscription.lastError}</p>}<div className="cardActions"><button type="button" onClick={() => mutate(subscription, `/api/upstream-subscriptions/${subscription.id}/refresh`, { method: "POST" })}>{text.refresh}</button><button type="button" onClick={() => beginEdit(subscription)}>{text.edit}</button><button type="button" onClick={() => mutate(subscription, `/api/upstream-subscriptions/${subscription.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: !subscription.enabled }) })}>{subscription.enabled ? text.disable : text.enable}</button><button type="button" className="dangerButton" onClick={() => remove(subscription)}>{text.remove}</button></div></article>)}</div>
  </section>;
}

function formatTraffic(subscription: UpstreamSubscription, unknown: string): string { if (typeof subscription.remainingTrafficBytes !== "number") return unknown; return `${formatBytes(subscription.remainingTrafficBytes)}${typeof subscription.trafficTotalBytes === "number" ? ` / ${formatBytes(subscription.trafficTotalBytes)}` : ""}`; }
function formatBytes(value: number): string { if (value < 1024 ** 2) return `${Math.round(value / 1024)} KB`; if (value < 1024 ** 3) return `${(value / 1024 ** 2).toFixed(1)} MB`; return `${(value / 1024 ** 3).toFixed(1)} GB`; }
function formatDate(value: string | undefined, unknown: string): string { if (!value) return unknown; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleString(); }
async function readResult(response: Response): Promise<Record<string, any>> { return response.json().catch(() => ({})); }
function requireOK(response: Response): Response { if (!response.ok) throw new Error(`HTTP ${response.status}`); return response; }
